-- ========================================================
-- AuraVibe Product Reviews & Support Ticket Policy Fixes
-- Migration: 20261007000005_product_reviews_and_support_fixes.sql
-- ========================================================

-- 1. Create product_reviews Table
CREATE TABLE IF NOT EXISTS public.product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  user_avatar TEXT,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for product_reviews
CREATE INDEX IF NOT EXISTS idx_product_reviews_product_id ON public.product_reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_product_reviews_user_id ON public.product_reviews(user_id);

-- Enable RLS on product_reviews
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;

-- RLS Policies for product_reviews
DROP POLICY IF EXISTS "Public view approved reviews, user view own, admin view all" ON public.product_reviews;
CREATE POLICY "Public view approved reviews, user view own, admin view all" ON public.product_reviews
  FOR SELECT USING (
    status = 'approved' OR
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users insert own review or admin insert" ON public.product_reviews;
CREATE POLICY "Users insert own review or admin insert" ON public.product_reviews
  FOR INSERT WITH CHECK (
    public.is_admin() OR
    (
      comment IS NOT NULL AND
      user_name IS NOT NULL AND
      rating >= 1 AND rating <= 5
    )
  );

DROP POLICY IF EXISTS "Users update own review or admin update" ON public.product_reviews;
CREATE POLICY "Users update own review or admin update" ON public.product_reviews
  FOR UPDATE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  ) WITH CHECK (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users delete own review or admin delete" ON public.product_reviews;
CREATE POLICY "Users delete own review or admin delete" ON public.product_reviews
  FOR DELETE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

-- 2. Update Support Tickets RLS Policies to allow lookup by phone or user_id
DROP POLICY IF EXISTS "Users view own tickets or admin view all" ON public.support_tickets;
CREATE POLICY "Users view own tickets or admin view all" ON public.support_tickets
  FOR SELECT USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())) OR
    customer_phone IN (SELECT phone FROM public.users WHERE auth_user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Users and Admins update tickets" ON public.support_tickets;
CREATE POLICY "Users and Admins update tickets" ON public.support_tickets
  FOR UPDATE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())) OR
    customer_phone IN (SELECT phone FROM public.users WHERE auth_user_id = auth.uid())
  ) WITH CHECK (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())) OR
    customer_phone IN (SELECT phone FROM public.users WHERE auth_user_id = auth.uid())
  );

-- 3. Enable Realtime publication for product_reviews
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.product_reviews;
  END IF;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
