-- ========================================================
-- AuraVibe User Cart & Wishlist Schema & RLS Migration
-- Migration: 20261007000004_cart_and_wishlist.sql
-- ========================================================

-- 1. user_carts table
CREATE TABLE IF NOT EXISTS public.user_carts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  color TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast lookup by user_id
CREATE INDEX IF NOT EXISTS idx_user_carts_user_id ON public.user_carts(user_id);

-- 2. user_wishlists table
CREATE TABLE IF NOT EXISTS public.user_wishlists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_wishlists_user_product_key UNIQUE(user_id, product_id)
);

-- Index for fast lookup by user_id
CREATE INDEX IF NOT EXISTS idx_user_wishlists_user_id ON public.user_wishlists(user_id);

-- 3. Enable Row Level Security
ALTER TABLE public.user_carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_wishlists ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for user_carts
DROP POLICY IF EXISTS "Users view own cart or admin view all" ON public.user_carts;
CREATE POLICY "Users view own cart or admin view all" ON public.user_carts
  FOR SELECT USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users insert own cart or admin insert" ON public.user_carts;
CREATE POLICY "Users insert own cart or admin insert" ON public.user_carts
  FOR INSERT WITH CHECK (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users update own cart or admin update" ON public.user_carts;
CREATE POLICY "Users update own cart or admin update" ON public.user_carts
  FOR UPDATE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  ) WITH CHECK (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users delete own cart or admin delete" ON public.user_carts;
CREATE POLICY "Users delete own cart or admin delete" ON public.user_carts
  FOR DELETE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

-- 5. RLS Policies for user_wishlists
DROP POLICY IF EXISTS "Users view own wishlist or admin view all" ON public.user_wishlists;
CREATE POLICY "Users view own wishlist or admin view all" ON public.user_wishlists
  FOR SELECT USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users insert own wishlist or admin insert" ON public.user_wishlists;
CREATE POLICY "Users insert own wishlist or admin insert" ON public.user_wishlists
  FOR INSERT WITH CHECK (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

DROP POLICY IF EXISTS "Users delete own wishlist or admin delete" ON public.user_wishlists;
CREATE POLICY "Users delete own wishlist or admin delete" ON public.user_wishlists
  FOR DELETE USING (
    public.is_admin() OR
    (auth.uid() IS NOT NULL AND user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid()))
  );

-- 6. Enable Realtime publication for cart and wishlist
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.user_carts, public.user_wishlists;
  END IF;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
